### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mcchrish** [feathersjs-ecosystem/feathers-mailgun#1]
Hi I'm having trouble sending a simple email. Might be an issue in mailgun-js.

```
❯ node example/app.js
TypeError: Cannot read property 'length' of undefined
    at Object.constructor.(anonymous function) [as _send] (/Users/mclopez/feathers-mailgun
/node_modules/mailgun-js/lib/build.js:49:20)
    at /Users/mclopez/feathers-mailgun/lib/index.js:55:15
    at new Promise (/Users/mclopez/feathers-mailgun/node_modules/core-js/modules/es6.promi
se.js:193:7)
    at Object.create (/Users/mclopez/feathers-mailgun/lib/index.js:53:14)
    at Object.wrapper (/Users/mclopez/feathers-mailgun/node_modules/feathers/lib/mixins/pr
omise.js:30:28)
    at Object.<anonymous> (/Users/mclopez/feathers-mailgun/node_modules/uberproto/lib/prot
o.js:30:17)
    at Object.wrapped (/Users/mclopez/feathers-mailgun/node_modules/rubberduck/lib/rubberd
uck.js:63:19)
    at Object.mixin.(anonymous function) (/Users/mclopez/feathers-mailgun/node_modules/fea
thers/lib/mixins/normalizer.js:17:32)
    at Object.create (/Users/mclopez/feathers-mailgun/node_modules/uberproto/lib/proto.js:
30:17)
    at Object.<anonymous> (/Users/mclopez/feathers-mailgun/example/app.js:26:23)
Feathers server listening on port 3030
```

**Comment by ekryski** [comment]
published v0.1.1 with the fix for this.
